# Generated by Django 2.1.5 on 2019-02-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190204_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'get_latest_by': ['-priority', '-date']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
